version: '3.5'

services:
  ugc:
    container_name: ugc
    image: ugc
    networks:
      - movies
    environment:
      KAFKA__HOST: broker
      KAFKA__PORT: 29092
      APP__JWT_SECRET_KEY: $APP__JWT_SECRET_KEY
      APP__ALGORITHM: HS256
    depends_on:
      - broker
    env_file:
      - .env

networks:
    movies:
      name: movies

volumes:
    postgres:
    pgadmin: